services:
  - type: web
    name: safarisalama-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: safarisalama-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.12.0

databases:
  - name: safarisalama-db
    databaseName: safarisalama
    user: safarisalama