name: safari_salama_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  google_maps_flutter: ^2.5.0
  geolocator: ^14.0.0
  flutter_dotenv: ^6.0.0
  intl: ^0.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/app_icon.png
    - assets/images/safari_salama_logo.png
    - .env